// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("o11yspanmetrics")
	ScopeName = "github.com/hanzoai/otel-collector/processor/o11yspanmetricsprocessor"
)

const (
	TracesStability = component.StabilityLevelBeta
)
