// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("datastoresystemtablesreceiver")
	ScopeName = "github.com/hanzoai/otel-collector/receiver/datastoresystemtablesreceiver"
)

const (
	LogsStability = component.StabilityLevelBeta
)
