// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("o11yawsfirehose")
	ScopeName = "github.com/hanzoai/otel-collector/receiver/o11yawsfirehosereceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
	LogsStability    = component.StabilityLevelAlpha
)
