// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("o11ykafkareceiver")
	ScopeName = "github.com/hanzoai/otel-collector/receiver/o11ykafkareceiver"
)

const (
	MetricsStability = component.StabilityLevelBeta
	LogsStability    = component.StabilityLevelBeta
	TracesStability  = component.StabilityLevelBeta
)
