// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("signozclickhousemetrics")
	ScopeName = "github.com/hanzoai/otel-collector/exporter/o11ydatastoremetrics"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
