// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("datastoretraces")
	ScopeName = "github.com/hanzoai/otel-collector/exporter/datastoretracesexporter"
)

const (
	TracesStability = component.StabilityLevelStable
)
