// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("datastorelogsexporter")
	ScopeName = "github.com/hanzoai/otel-collector/exporter/datastorelogsexporter"
)

const (
	LogsStability = component.StabilityLevelStable
)
