// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("o11ymeter")
	ScopeName = "github.com/hanzoai/otel-collector/connectors/o11ymeterconnector"
)

const (
	TracesToMetricsStability  = component.StabilityLevelBeta
	MetricsToMetricsStability = component.StabilityLevelBeta
	LogsToMetricsStability    = component.StabilityLevelBeta
)
